language: python
install:
  - pip install -r requirements.txt -r test-requirements.txt
script:
  - flake8
  - nosetests --verbose --with-cov --cov-report xml --cover-package=emailer
after_success:
  - coveralls
